<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEXbTxtx\srcApp_Kernel.envDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEXbTxtx/srcApp_Kernel.envDebugContainer.php') {
    touch(__DIR__.'/ContainerEXbTxtx.legacy');

    return;
}

if (!\class_exists(srcApp_Kernel.envDebugContainer::class, false)) {
    \class_alias(\ContainerEXbTxtx\srcApp_Kernel.envDebugContainer::class, srcApp_Kernel.envDebugContainer::class, false);
}

return new \ContainerEXbTxtx\srcApp_Kernel.envDebugContainer([
    'container.build_hash' => 'EXbTxtx',
    'container.build_id' => 'a536f8e2',
    'container.build_time' => 1550147789,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEXbTxtx');
