<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBWaysGK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBWaysGK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBWaysGK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBWaysGK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBWaysGK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BWaysGK',
    'container.build_id' => '6362c8de',
    'container.build_time' => 1550179330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBWaysGK');
