<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMftBvdT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMftBvdT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMftBvdT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMftBvdT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMftBvdT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MftBvdT',
    'container.build_id' => '2d77465f',
    'container.build_time' => 1550140469,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMftBvdT');
